# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AnimationData": types.AnimationData,
    "stream_types.AnimationData": stream_types.AnimationData,

    "types.ProblemData": types.ProblemData,
    "stream_types.ProblemData": stream_types.ProblemData,


    "types.Environments": types.Environments,

    "types.Forces": types.Forces,

    "types.Interactions": types.Interactions,

    "types.Motions": types.Motions,

    "types.Objects": types.Objects,

}